/** Declaration file generated by dts-gen */

declare module 'text-to-image' {


  type dataUrl = string;
  interface configuration {

     debug?: boolean;
     maxWidth?: number;
     fontSize?: number;
     lineHeight?: number;
     margin?: number;
     bgColor?: string;
     textColor?: string;
     fontFamily?: string;
     fontWeight?: string;
     customHeight?: number;
     textAlign?: string;
    
  }

  export function generate(content: string, config?: configuration): Promise<dataUrl>;

  export function generateSync(content: string, config?: configuration): Promise<dataUrl>;

}


